insert into roles (name) values ('user');
insert into roles (name) values ('coach');
insert into groups (name, description) values ('juniors', '12+ y.o.');
insert into groups (name, description) values ('kids', '6 - 12 y.o.');
insert into plans (type, price) values ('twice_in_week', 60);
insert into plans (type, price) values ('full', 70);
insert into user_roles (user_id, role_id) values (1, 1);
insert into user_roles (user_id, role_id) values (2, 1);
insert into user_roles (user_id, role_id) values (2, 2);
insert into events ("event_type", uniform, start, "end") values ('class', 'Gi', '2025.08.14 18:00', '2025.08.14 20:00');
insert into achievements(user_id ,date, type, description) values (1, '2025.02.03', 'gold medal', 'some comments here' );
insert into event_groups(event_id, group_id) values (1, 1);